name: Slurp
favicon: null
layout_spectrum: 0.74444
typography_spectrum: 0.63019
title: Slurp
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e64d6'
    - '#ff84c3'
    - '#9c5b00'
    - '#f7d729'
    - '#1a0000'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
