title: Slurp
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.375
  brandStrength: 1
  lightness: 0.5625
  brandColors:
    - '#2e64d6'
    - '#ff84c3'
    - '#9c5b00'
    - '#f7d729'
    - '#1a0000'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Slurp
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.63019
layout_spectrum: 0.74444
